Hard/F22Exam/config/routes.rb
Rails.application.routes.draw do

  

  get 'students/signup'

  get 'welcome/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#home"

  resources :students
  get '/signup', to: 'students#signup'
end

Hard/F22Exam/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Hard/F22Exam/app/models/student.rb
class Student < ApplicationRecord
  has_secure_password
end

Hard/F22Exam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Hard/F22Exam/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def signup

  end
end

Hard/F22Exam/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def signup
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student.user_name)
    else
      flash[:danger] = "Invalid username/password combination."
      redirect_to(:action => "new")
    end
  end

private
  def student_params
    params.require(:students).permit(:user_name,:fname,:lname,:email,:password,:password_confirmation)
  end


end

Hard/F22Exam/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

Hard/F22Exam/app/helpers/application_helper.rb
module ApplicationHelper
end

Hard/F22Exam/app/helpers/sessions_helper.rb
module SessionsHelper
end

Hard/F22Exam/app/helpers/students_helper.rb
module StudentsHelper
end

Hard/F22Exam/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Hard/F22Exam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>F22 Exams</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'download.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-brand">
          <%=link_to "F22 Exams","/",padding_top: "15px",float: "none",margin: "0"%>
        </div>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="#">Help</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Help</a></li>
      </ul>

      <ul class= "nav navbar-nav navbar-right">
          <li><a href="#">Help</a></li>
          <li><a href="#">Help</a></li>
          <li><%= link_to "Sign Up",signup_path%></li>
      </ul>
    </div>
  </nav>



</head>

<body>
  <%= yield %>
</body>
<div class="container">

  <%= debug(params) if Rails.env.development? %>
</div>
</html>

Hard/F22Exam/app/views/students/new.html.erb
<h1>User Created</h1/>

Hard/F22Exam/app/views/students/show.html.erb
<h1>User  Created</h1>

Hard/F22Exam/app/views/students/signup.html.erb
<h1>Students#signup</h1>
<p>Find me in app/views/students/signup.html.erb</p>


<div class="col-md-6 col-md-offset-3">
    <%= form_for :students, url: students_path, html: {method: :post} do |f| %>
    <div class="form-group">
      <%= f.label :"user name" %>
      <%= f.text_field :user_name,class:'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :"email" %>
      <%= f.text_field :email,class:'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :"First Name" %>
      <%= f.text_field :fname ,class:'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :"Last Name" %>
      <%= f.text_field :lname ,class:'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :"password" %>
      <%= f.password_field :password ,class:'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :"password confirmation" %>
      <%= f.password_field :password_confirmation ,class:'form-control'%>
    </div>
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
  </div>

Hard/F22Exam/app/views/welcome/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to F22 Exams</h1>
  
  </div>
</div>